---
- name: Configure Kubernetes Hosts
  hosts: kubernetes
  become: true

  tasks:
    - name: Add Hostname To /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{ inventory_hostname }}.kubernetes.local {{ inventory_hostname }}"
      become: true
    - name: Change Hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      become: true
